apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 1s
    scrape_configs:
      - job_name: 'prometheus'
        metrics_path: '/actuator/prometheus'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: spring


# 아래는 Data 부분에 대한 설명

# data:
#   prometheus.yml: |
#     global:                             # Prometheus 전역 설정
#       scrape_interval: 1s               # Prometheus가 메트릭을 가져오는 간격을 지정합니다 (1초마다 가져옵니다).

#     scrape_configs:                     # 스크랩 구성 목록
#       - job_name: 'prometheus'          # 스크랩 작업에 대한 고유 식별자
#         metrics_path: '/actuator/prometheus'  # 메트릭이 타겟에 의해 노출되는 경로를 지정합니다.

#         kubernetes_sd_configs:          # Kubernetes 서비스 검색 구성
#         - role: endpoints               # Kubernetes 서비스 검색의 역할 (endpoints 역할인 경우)

#           namespaces:                   # 검색할 네임스페이스를 지정합니다.
#             names:                      # 네임스페이스 이름의 목록
#               - default                 # 'default'라는 네임스페이스 이름

#         relabel_configs:                 # 검색된 타겟에 대한 라벨 재구성 구성 목록
#           - source_labels: [__meta_kubernetes_service_label_app]  # Kubernetes 서비스 메타데이터에서 가져온 라벨
#             action: keep                 # 라벨에 대해 수행할 동작을 지정합니다.
#             regex: spring                # 라벨 값과 일치하는 정규 표현식 (값이 'spring'인 것만 유지)
